//
//  HPolygonalRadarEnumDefine.h
//  HPolygonalRadar
//
//  Created by 何正道 on 2019/4/19.
//  Copyright © 2019 何正道. All rights reserved.
//

#ifndef HPolygonalRadarEnumDefine_h
#define HPolygonalRadarEnumDefine_h

/**
 雷达图背景风格

 - ENUM_HPOLYGONALRADAR_BG_STYLE_DEFAULT: 默认背景
 - ENUM_HPOLYGONALRADAR_BG_STYLE_CUSTOM_IMAGE: 自定义图片
 */
typedef NS_ENUM(NSUInteger, ENUM_HPOLYGONALRADAR_BG_STYLE) {
    ENUM_HPOLYGONALRADAR_BG_STYLE_DEFAULT,
    ENUM_HPOLYGONALRADAR_BG_STYLE_CUSTOM_IMAGE
};

/**
 雷达图顶点Icon风格

 - ENUM_HPOLYGONALRADAR_VERTEX_ICON_STYLE_SOLID_CIRCLE: 实心圆Icon
 - ENUM_HPOLYGONALRADAR_VERTEX_ICON_STYLE_HOLLOW_CIRCLE: 空心圆Icon
 */
typedef NS_ENUM(NSUInteger, ENUM_HPOLYGONALRADAR_VERTEX_ICON_STYLE) {
    ENUM_HPOLYGONALRADAR_VERTEX_ICON_STYLE_SOLID_CIRCLE,
    ENUM_HPOLYGONALRADAR_VERTEX_ICON_STYLE_HOLLOW_CIRCLE
};

/**
 雷达图填充风格

 - ENUM_HPOLYGONALRADAR_FILL_STYLE_SOLID_COLOR: 纯色填充
 - ENUM_HPOLYGONALRADAR_FILL_STYLE_GRADIENT_COLOR: 渐变色填充
 */
typedef NS_ENUM(NSUInteger, ENUM_HPOLYGONALRADAR_FILL_STYLE) {
    ENUM_HPOLYGONALRADAR_FILL_STYLE_SOLID_COLOR,
    ENUM_HPOLYGONALRADAR_FILL_STYLE_GRADIENT_COLOR
};

/**
 雷达图线条风格

 - ENUM_HPOLYGONALRADAR_LINE_STYLE_SOLID_LINE: 实线
 - ENUM_HPOLYGONALRADAR_LINE_STYLE_DASH_LINE: 虚线
 */
typedef NS_ENUM(NSUInteger, ENUM_HPOLYGONALRADAR_LINE_STYLE) {
    ENUM_HPOLYGONALRADAR_LINE_STYLE_SOLID_LINE,
    ENUM_HPOLYGONALRADAR_LINE_STYLE_DASH_LINE
};

#endif /* HPolygonalRadarEnumDefine_h */
